### ISSUE TITLE
Duplicate project

### ISSUE THREAD

**Issue by mbugeia** [CotzaDev/seafile_ynh#1]
Hi,

I did package seafile for yunohost too a few days ago here: https://github.com/mbugeia/seafile_ynh

My implementation differ by a few point:
 - use of mysql instead of sqlite
 - no sso hack, (but kind of, I use persistent config of ssowat), all client work fine
 - email configuration

I did not test your solution but are you sure that https syncing works ? You seems use a domain.tld/seafile/seafhttp path for this but seafile server doc say explicitly that the url must be domain.tld/seafhttp (cf: http://manual.seafile.com/deploy/deploy_http_sync.html). 

Maybe we should consider merging project by taking the best of both project. What do you think ?

**Comment by CotzaDev** [comment]
Hi,

I'm surprise to see you made a package of seafile for yunohost. I have searched for seafile packages but I have only found a very old implementation.

So:
* domain.tld/seafile/seafhttp work fine with sync clients (I have tested with the mac and the ios client), you have to put https://domain.tld/seafile in the server address field. I think the doc say to use domain.tld/seafhttp in case the installation is at root.
* I think my sso hack is maybe a proper solution because I don't change any yunohost files.
* I agree that I should use mysql and configure email in my implementation.

I am open at the idea of merging our two projects.

**Comment by mbugeia** [comment]
Well my seafile package is new too (like 5 days) so it's not surprising that you did not find it.

Did you just test client or real http sync? Http sync is not the default on seafile client. Best way to test it is to block all seafile specific port since it use ssl port and try to sync the desktop client. You may have to disable ssl cert check if you have a self signed certificate. I need to test my version again with your config. 

With seafile server 4.1 version I've planned to not open any port by default since http syncing will be the default.

If we can use a path like domain.tld/seafile/seafhttp for http syncing I think there is no need for a sso hack because we can do all the config with yunohost app setting command. 

My workaround was about bypassing yunohost helpers that can pass unprotected_uris but not unprotected_urls. It modify a file that is not modified automatically by yunohost, it's for custom settings.

I appreciate that you have merge some of my scripts in yours but be aware that I address a few more things that cause bugs with yours. For example the remove script don't remove mysql database, that cause error on a reinstall. 

Moreover there are security concern in your version:
 - The init script run seafile with root user (btw there is no need to put the init script in 2 place)
 - seahub port should not be open behind nginx
 - It's better to give proper permission to the install path

**Comment by CotzaDev** [comment]
I have test real http sync and it works.

Yes, we can use domain.tld/seafile/seafhttp but we can't avoid the hack because the lua script used for the access control on nginx check `ngx.var.uri` and with this rewrite `rewrite ^/seafile/seafhttp(.*)$ $1 break;` nginx store inside only what is after `/seafhttp`. For example `/upload-api` and not `/seafile/seafhttp/upload-api`. I spent an night this ...

I added the remove mysql database script and removed one of the init scripts (I don't know why there was two cp ...)

I will try to fix the security concern when I have time. Maybe tomorrow.
